
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Feb 24 21:23:44 GMT-06:00 2022
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Conjunto = 4;
  public static final int Numero = 17;
  public static final int Mas = 18;
  public static final int LlaveCierre = 3;
  public static final int ERROR = 23;
  public static final int Identificador = 16;
  public static final int Coma = 20;
  public static final int Separador = 5;
  public static final int Asterisco = 12;
  public static final int Asignador = 7;
  public static final int Cadena = 22;
  public static final int Negativo = 15;
  public static final int EOF = 0;
  public static final int ComillaSimple = 21;
  public static final int LlaveAbre = 2;
  public static final int Rango = 8;
  public static final int Comilla = 13;
  public static final int Interrogacion = 19;
  public static final int error = 1;
  public static final int Punto = 11;
  public static final int SaltoLinea = 10;
  public static final int Barra = 14;
  public static final int PuntoComa = 9;
  public static final int DosPuntos = 6;
}

